# Generated by Django 5.2.15 on 2026-06-11 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrn_encoded', models.CharField(db_index=True, max_length=40, unique=True)),
                ('name_encrypted', models.BinaryField()),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('Other', 'Other')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TriageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('chief_complaint', models.TextField(max_length=2000)),
                ('vitals', models.JSONField(default=dict)),
                ('oncology_context', models.JSONField(default=dict)),
                ('acuity', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('oncologic_emergency_flags', models.JSONField(default=list)),
                ('extractor_status', models.CharField(choices=[('ok', 'ok'), ('failed', 'failed'), ('timeout', 'timeout')], default='ok', max_length=16)),
                ('audit_user', models.CharField(blank=True, max_length=80, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='triage.patient')),
            ],
            options={
                'ordering': ['acuity', 'timestamp'],
            },
        ),
    ]
